import { StyleSheet } from "@react-pdf/renderer";
import { PDF_BRAND } from "@/lib/pdf/quote/branding";

export const schedulePdfStyles = StyleSheet.create({
  page: {
    fontFamily: PDF_BRAND.fonts.body,
    fontSize: 10,
    color: PDF_BRAND.colors.primary,
    backgroundColor: PDF_BRAND.colors.background,
    paddingTop: 40,
    paddingBottom: 50,
    paddingHorizontal: 48,
    lineHeight: 1.5,
  },
  headerBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 6,
    backgroundColor: PDF_BRAND.colors.accent,
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 48,
    right: 48,
    borderTopWidth: 1,
    borderTopColor: PDF_BRAND.colors.border,
    paddingTop: 8,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  footerText: {
    fontSize: 8,
    color: PDF_BRAND.colors.muted,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 24,
  },
  agencyName: {
    fontFamily: PDF_BRAND.fonts.heading,
    fontSize: 22,
    color: PDF_BRAND.colors.primary,
    letterSpacing: -0.5,
  },
  agencyTagline: {
    fontSize: 9,
    color: PDF_BRAND.colors.muted,
    marginTop: 2,
  },
  docLabel: {
    fontSize: 9,
    color: PDF_BRAND.colors.muted,
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 4,
  },
  docTitle: {
    fontFamily: PDF_BRAND.fonts.heading,
    fontSize: 14,
    color: PDF_BRAND.colors.accent,
    maxWidth: 220,
    textAlign: "right",
  },
  versionBadge: {
    fontSize: 9,
    color: PDF_BRAND.colors.muted,
    marginTop: 4,
    textAlign: "right",
  },
  metaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    marginBottom: 20,
    padding: 14,
    backgroundColor: PDF_BRAND.colors.surface,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: PDF_BRAND.colors.border,
  },
  metaItem: {
    width: "30%",
    minWidth: 120,
  },
  metaLabel: {
    fontSize: 8,
    color: PDF_BRAND.colors.muted,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 3,
  },
  metaValue: {
    fontFamily: PDF_BRAND.fonts.heading,
    fontSize: 10,
    color: PDF_BRAND.colors.primary,
  },
  sectionTitle: {
    fontFamily: PDF_BRAND.fonts.heading,
    fontSize: 12,
    color: PDF_BRAND.colors.primary,
    marginBottom: 10,
    marginTop: 8,
    paddingBottom: 6,
    borderBottomWidth: 2,
    borderBottomColor: PDF_BRAND.colors.accent,
  },
  overviewGrid: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 20,
  },
  overviewCard: {
    flex: 1,
    padding: 12,
    backgroundColor: PDF_BRAND.colors.surface,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: PDF_BRAND.colors.border,
  },
  overviewValue: {
    fontFamily: PDF_BRAND.fonts.heading,
    fontSize: 16,
    color: PDF_BRAND.colors.accent,
    marginBottom: 2,
  },
  overviewLabel: {
    fontSize: 8,
    color: PDF_BRAND.colors.muted,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  timelineContainer: {
    marginBottom: 20,
  },
  timelineWeekRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: PDF_BRAND.colors.border,
    marginLeft: 100,
  },
  timelineWeekCell: {
    paddingVertical: 4,
    paddingHorizontal: 2,
    borderRightWidth: 1,
    borderRightColor: PDF_BRAND.colors.border,
    alignItems: "center",
  },
  weekLabel: {
    fontFamily: PDF_BRAND.fonts.heading,
    fontSize: 8,
    color: PDF_BRAND.colors.primary,
  },
  weekDate: {
    fontSize: 6,
    color: PDF_BRAND.colors.muted,
    marginTop: 1,
  },
  phaseRow: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 28,
    borderBottomWidth: 1,
    borderBottomColor: PDF_BRAND.colors.border,
  },
  phaseLabel: {
    width: 100,
    fontSize: 8,
    color: PDF_BRAND.colors.primary,
    paddingRight: 8,
  },
  phaseTrack: {
    flex: 1,
    height: 22,
    position: "relative",
  },
  phaseBar: {
    position: "absolute",
    top: 4,
    height: 14,
    borderRadius: 3,
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  phaseBarText: {
    fontSize: 6,
    color: "#ffffff",
  },
  milestoneRow: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 32,
    marginTop: 4,
  },
  milestoneTrack: {
    flex: 1,
    height: 24,
    position: "relative",
  },
  milestoneDiamond: {
    position: "absolute",
    top: 6,
    width: 10,
    height: 10,
    transform: "rotate(45deg)",
    borderWidth: 1,
    borderColor: "#ffffff",
  },
  legendRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 8,
    marginBottom: 16,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  legendDiamond: {
    width: 6,
    height: 6,
    transform: "rotate(45deg)",
  },
  legendText: {
    fontSize: 7,
    color: PDF_BRAND.colors.muted,
  },
  deliverableItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 6,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: PDF_BRAND.colors.border,
  },
  deliverableBullet: {
    width: 14,
    fontSize: 10,
    color: PDF_BRAND.colors.accent,
  },
  deliverableText: {
    flex: 1,
    fontSize: 9,
    color: PDF_BRAND.colors.primary,
  },
  notesBox: {
    marginTop: 16,
    padding: 12,
    backgroundColor: PDF_BRAND.colors.surface,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: PDF_BRAND.colors.border,
  },
  notesText: {
    fontSize: 9,
    color: PDF_BRAND.colors.primary,
    lineHeight: 1.6,
  },
});
