-- Generated by scripts/bundle-migrations.mjs — run in Supabase SQL Editor (in order)
-- 26 migration files

-- =============================================================================
-- 20260629000001_extensions_and_enums.sql
-- =============================================================================

-- Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Enum types
CREATE TYPE public.opportunity_status AS ENUM (
  'new',
  'reviewing',
  'qualified',
  'contacted',
  'proposal_sent',
  'won',
  'lost',
  'archived'
);

CREATE TYPE public.client_status AS ENUM (
  'prospect',
  'onboarding',
  'active',
  'inactive',
  'churned'
);

CREATE TYPE public.project_status AS ENUM (
  'draft',
  'active',
  'on_hold',
  'in_review',
  'completed',
  'cancelled'
);

CREATE TYPE public.quote_status AS ENUM (
  'draft',
  'sent',
  'approved',
  'rejected',
  'expired'
);

-- =============================================================================
-- 20260629000002_profiles.sql
-- =============================================================================

-- Profiles table links Supabase Auth users to the application
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  full_name TEXT,
  avatar_url TEXT,
  role TEXT NOT NULL DEFAULT 'member',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.profiles IS 'Application user profiles linked to Supabase Auth';

-- Auto-create profile on user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'full_name', NEW.email),
    NEW.raw_user_meta_data ->> 'avatar_url'
  );
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- =============================================================================
-- 20260629000003_core_tables.sql
-- =============================================================================

-- Companies
CREATE TABLE public.companies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_name TEXT NOT NULL,
  website TEXT,
  industry TEXT,
  ai_summary TEXT,
  estimated_size TEXT,
  headquarters TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.companies IS 'Organisations discovered or managed within Dissembargo OS';

-- Contacts
CREATE TABLE public.contacts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES public.companies (id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  role TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.contacts IS 'People associated with companies';

-- Opportunities (AI-qualified inbox entries)
CREATE TABLE public.opportunities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES public.companies (id) ON DELETE CASCADE,
  contact_id UUID REFERENCES public.contacts (id) ON DELETE SET NULL,
  subject TEXT,
  email_body TEXT,
  ai_category TEXT,
  ai_confidence NUMERIC(5, 2) CHECK (ai_confidence >= 0 AND ai_confidence <= 100),
  opportunity_status public.opportunity_status NOT NULL DEFAULT 'new',
  estimated_budget NUMERIC(12, 2),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.opportunities IS 'AI-qualified potential client opportunities from analysed emails';

-- Clients
CREATE TABLE public.clients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID NOT NULL REFERENCES public.companies (id) ON DELETE CASCADE,
  client_status public.client_status NOT NULL DEFAULT 'prospect',
  onboarding_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT clients_company_id_unique UNIQUE (company_id)
);

COMMENT ON TABLE public.clients IS 'Converted companies with an active or historical client relationship';

-- Projects
CREATE TABLE public.projects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID NOT NULL REFERENCES public.clients (id) ON DELETE CASCADE,
  project_name TEXT NOT NULL,
  status public.project_status NOT NULL DEFAULT 'draft',
  start_date DATE,
  delivery_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.projects IS 'Creative projects delivered for clients';

-- Quotes
CREATE TABLE public.quotes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES public.projects (id) ON DELETE CASCADE,
  quote_status public.quote_status NOT NULL DEFAULT 'draft',
  subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0,
  discount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  total NUMERIC(12, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.quotes IS 'Financial quotes associated with projects';

-- Production Schedules
CREATE TABLE public.production_schedules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES public.projects (id) ON DELETE CASCADE,
  version INTEGER NOT NULL DEFAULT 1,
  schedule_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT production_schedules_project_version_unique UNIQUE (project_id, version)
);

COMMENT ON TABLE public.production_schedules IS 'Versioned production schedule data per project';

-- =============================================================================
-- 20260629000004_indexes.sql
-- =============================================================================

-- Companies
CREATE INDEX idx_companies_company_name ON public.companies (company_name);
CREATE INDEX idx_companies_created_at ON public.companies (created_at DESC);

-- Contacts
CREATE INDEX idx_contacts_company_id ON public.contacts (company_id);
CREATE INDEX idx_contacts_email ON public.contacts (email) WHERE email IS NOT NULL;

-- Opportunities
CREATE INDEX idx_opportunities_company_id ON public.opportunities (company_id);
CREATE INDEX idx_opportunities_contact_id ON public.opportunities (contact_id) WHERE contact_id IS NOT NULL;
CREATE INDEX idx_opportunities_status ON public.opportunities (opportunity_status);
CREATE INDEX idx_opportunities_created_at ON public.opportunities (created_at DESC);
CREATE INDEX idx_opportunities_ai_confidence ON public.opportunities (ai_confidence DESC NULLS LAST);

-- Clients
CREATE INDEX idx_clients_company_id ON public.clients (company_id);
CREATE INDEX idx_clients_status ON public.clients (client_status);

-- Projects
CREATE INDEX idx_projects_client_id ON public.projects (client_id);
CREATE INDEX idx_projects_status ON public.projects (status);
CREATE INDEX idx_projects_delivery_date ON public.projects (delivery_date) WHERE delivery_date IS NOT NULL;

-- Quotes
CREATE INDEX idx_quotes_project_id ON public.quotes (project_id);
CREATE INDEX idx_quotes_status ON public.quotes (quote_status);

-- Production Schedules
CREATE INDEX idx_production_schedules_project_id ON public.production_schedules (project_id);

-- =============================================================================
-- 20260629000005_updated_at_triggers.sql
-- =============================================================================

-- Reusable updated_at trigger function
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER set_companies_updated_at
  BEFORE UPDATE ON public.companies
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_contacts_updated_at
  BEFORE UPDATE ON public.contacts
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_opportunities_updated_at
  BEFORE UPDATE ON public.opportunities
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_clients_updated_at
  BEFORE UPDATE ON public.clients
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_projects_updated_at
  BEFORE UPDATE ON public.projects
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_quotes_updated_at
  BEFORE UPDATE ON public.quotes
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_production_schedules_updated_at
  BEFORE UPDATE ON public.production_schedules
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =============================================================================
-- 20260629000006_row_level_security.sql
-- =============================================================================

-- Enable Row Level Security on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.opportunities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.production_schedules ENABLE ROW LEVEL SECURITY;

-- Profiles: users can read all profiles, update only their own
CREATE POLICY "profiles_select_authenticated"
  ON public.profiles FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "profiles_update_own"
  ON public.profiles FOR UPDATE
  TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- Shared policy pattern: authenticated agency users have full access
-- (single-tenant internal app; extend with org scoping when needed)

CREATE POLICY "companies_all_authenticated"
  ON public.companies FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "contacts_all_authenticated"
  ON public.contacts FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "opportunities_all_authenticated"
  ON public.opportunities FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "clients_all_authenticated"
  ON public.clients FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "projects_all_authenticated"
  ON public.projects FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "quotes_all_authenticated"
  ON public.quotes FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "production_schedules_all_authenticated"
  ON public.production_schedules FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- =============================================================================
-- 20260629000007_storage.sql
-- =============================================================================

-- Storage buckets for Dissembargo OS
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES
  (
    'email-attachments',
    'email-attachments',
    false,
    26214400,
    ARRAY[
      'application/pdf',
      'image/jpeg',
      'image/png',
      'image/webp',
      'image/gif',
      'text/plain',
      'text/csv',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    ]
  ),
  (
    'project-assets',
    'project-assets',
    false,
    104857600,
    ARRAY[
      'application/pdf',
      'image/jpeg',
      'image/png',
      'image/webp',
      'image/gif',
      'image/svg+xml',
      'video/mp4',
      'video/quicktime',
      'application/zip'
    ]
  ),
  (
    'documents',
    'documents',
    false,
    52428800,
    ARRAY[
      'application/pdf',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'text/plain',
      'text/csv'
    ]
  )
ON CONFLICT (id) DO NOTHING;

-- Storage RLS: authenticated users can manage files in all buckets
CREATE POLICY "storage_authenticated_select"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (bucket_id IN ('email-attachments', 'project-assets', 'documents'));

CREATE POLICY "storage_authenticated_insert"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id IN ('email-attachments', 'project-assets', 'documents'));

CREATE POLICY "storage_authenticated_update"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (bucket_id IN ('email-attachments', 'project-assets', 'documents'))
  WITH CHECK (bucket_id IN ('email-attachments', 'project-assets', 'documents'));

CREATE POLICY "storage_authenticated_delete"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (bucket_id IN ('email-attachments', 'project-assets', 'documents'));

-- =============================================================================
-- 20260629000008_opportunity_status_update.sql
-- =============================================================================

-- Update opportunity_status enum to match product requirements
ALTER TABLE public.opportunities
  ALTER COLUMN opportunity_status DROP DEFAULT;

CREATE TYPE public.opportunity_status_new AS ENUM (
  'new',
  'contacted',
  'quote_requested',
  'quote_sent',
  'won',
  'lost',
  'archived'
);

ALTER TABLE public.opportunities
  ALTER COLUMN opportunity_status TYPE public.opportunity_status_new
  USING (
    CASE opportunity_status::text
      WHEN 'reviewing' THEN 'new'::public.opportunity_status_new
      WHEN 'qualified' THEN 'new'::public.opportunity_status_new
      WHEN 'contacted' THEN 'contacted'::public.opportunity_status_new
      WHEN 'proposal_sent' THEN 'quote_sent'::public.opportunity_status_new
      WHEN 'new' THEN 'new'::public.opportunity_status_new
      WHEN 'won' THEN 'won'::public.opportunity_status_new
      WHEN 'lost' THEN 'lost'::public.opportunity_status_new
      WHEN 'archived' THEN 'archived'::public.opportunity_status_new
      ELSE 'new'::public.opportunity_status_new
    END
  );

DROP TYPE public.opportunity_status;

ALTER TYPE public.opportunity_status_new RENAME TO opportunity_status;

ALTER TABLE public.opportunities
  ALTER COLUMN opportunity_status SET DEFAULT 'new';

-- =============================================================================
-- 20260629000009_gmail_inbox.sql
-- =============================================================================

-- Gmail OAuth connections (tokens accessed server-side only)
CREATE TABLE public.gmail_connections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL UNIQUE REFERENCES auth.users (id) ON DELETE CASCADE,
  gmail_address TEXT NOT NULL,
  access_token TEXT NOT NULL,
  refresh_token TEXT NOT NULL,
  token_expiry TIMESTAMPTZ,
  history_id TEXT,
  last_sync_at TIMESTAMPTZ,
  last_sync_status TEXT NOT NULL DEFAULT 'pending',
  last_sync_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.gmail_connections IS 'Gmail OAuth credentials per user for read-only inbox sync';

-- Imported inbox emails (independent from Opportunities)
CREATE TABLE public.inbox (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  gmail_message_id TEXT NOT NULL,
  thread_id TEXT,
  subject TEXT,
  sender_name TEXT,
  sender_email TEXT,
  recipient TEXT,
  date_received TIMESTAMPTZ NOT NULL,
  body_plain TEXT,
  body_html TEXT,
  attachments JSONB NOT NULL DEFAULT '[]'::JSONB,
  is_read BOOLEAN NOT NULL DEFAULT false,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT inbox_user_message_unique UNIQUE (user_id, gmail_message_id)
);

COMMENT ON TABLE public.inbox IS 'Emails imported from Gmail inbox for review before AI processing';

CREATE INDEX idx_inbox_user_id ON public.inbox (user_id);
CREATE INDEX idx_inbox_date_received ON public.inbox (date_received DESC);
CREATE INDEX idx_inbox_is_read ON public.inbox (is_read);
CREATE INDEX idx_inbox_imported_at ON public.inbox (imported_at DESC);
CREATE INDEX idx_gmail_connections_user_id ON public.gmail_connections (user_id);

CREATE TRIGGER set_gmail_connections_updated_at
  BEFORE UPDATE ON public.gmail_connections
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =============================================================================
-- 20260629000010_gmail_inbox_rls.sql
-- =============================================================================

ALTER TABLE public.gmail_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inbox ENABLE ROW LEVEL SECURITY;

-- Users can view their own connection metadata (tokens excluded via server-only queries)
CREATE POLICY "gmail_connections_select_own"
  ON public.gmail_connections FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "gmail_connections_delete_own"
  ON public.gmail_connections FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- Inbox: users can only access their own imported emails
CREATE POLICY "inbox_select_own"
  ON public.inbox FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "inbox_update_own"
  ON public.inbox FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Inserts handled by service role during sync (no client insert policy)

-- =============================================================================
-- 20260629000011_ai_qualification.sql
-- =============================================================================

-- AI email classification categories
CREATE TYPE public.ai_email_category AS ENUM (
  'new_business_opportunity',
  'existing_client',
  'supplier',
  'invoice',
  'marketing',
  'recruitment',
  'spam',
  'other'
);

CREATE TYPE public.inbox_review_status AS ENUM (
  'pending_review',
  'approved',
  'rejected',
  'auto_created'
);

CREATE TYPE public.ai_processing_status AS ENUM (
  'pending',
  'processing',
  'completed',
  'failed'
);

-- Extend inbox with AI qualification fields
ALTER TABLE public.inbox
  ADD COLUMN ai_category public.ai_email_category,
  ADD COLUMN ai_confidence NUMERIC(5, 2) CHECK (ai_confidence >= 0 AND ai_confidence <= 100),
  ADD COLUMN ai_summary TEXT,
  ADD COLUMN ai_reasoning TEXT,
  ADD COLUMN ai_signature TEXT,
  ADD COLUMN ai_processed_at TIMESTAMPTZ,
  ADD COLUMN ai_processing_status public.ai_processing_status NOT NULL DEFAULT 'pending',
  ADD COLUMN ai_processing_error TEXT,
  ADD COLUMN review_status public.inbox_review_status,
  ADD COLUMN opportunity_id UUID REFERENCES public.opportunities (id) ON DELETE SET NULL,
  ADD COLUMN detected_company_name TEXT,
  ADD COLUMN detected_website TEXT;

-- Link opportunities back to source inbox email
ALTER TABLE public.opportunities
  ADD COLUMN inbox_id UUID REFERENCES public.inbox (id) ON DELETE SET NULL;

CREATE INDEX idx_inbox_ai_processing_status ON public.inbox (ai_processing_status);
CREATE INDEX idx_inbox_review_status ON public.inbox (review_status);
CREATE INDEX idx_inbox_opportunity_id ON public.inbox (opportunity_id);
CREATE INDEX idx_opportunities_inbox_id ON public.opportunities (inbox_id);

-- AI classification audit log
CREATE TABLE public.ai_classification_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  inbox_id UUID NOT NULL REFERENCES public.inbox (id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  ai_category public.ai_email_category,
  ai_confidence NUMERIC(5, 2),
  ai_summary TEXT,
  ai_reasoning TEXT,
  model TEXT NOT NULL,
  prompt_version TEXT NOT NULL DEFAULT 'v1',
  raw_response JSONB,
  action_taken TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_ai_classification_logs_inbox_id ON public.ai_classification_logs (inbox_id);
CREATE INDEX idx_ai_classification_logs_user_id ON public.ai_classification_logs (user_id);
CREATE INDEX idx_ai_classification_logs_created_at ON public.ai_classification_logs (created_at DESC);

COMMENT ON TABLE public.ai_classification_logs IS 'Audit log of all AI email classification decisions';

-- =============================================================================
-- 20260629000012_ai_qualification_rls.sql
-- =============================================================================

ALTER TABLE public.ai_classification_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "ai_classification_logs_select_own"
  ON public.ai_classification_logs FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- Inserts handled server-side via service role during processing

-- =============================================================================
-- 20260629000013_company_intelligence.sql
-- =============================================================================

-- Company Intelligence: extended fields for AI research, deduplication, and profile management

ALTER TABLE public.companies
  ADD COLUMN logo_url TEXT,
  ADD COLUMN products TEXT[] DEFAULT '{}',
  ADD COLUMN services TEXT[] DEFAULT '{}',
  ADD COLUMN key_markets TEXT[] DEFAULT '{}',
  ADD COLUMN target_customers TEXT[] DEFAULT '{}',
  ADD COLUMN creative_opportunities TEXT[] DEFAULT '{}',
  ADD COLUMN suggested_services TEXT[] DEFAULT '{}',
  ADD COLUMN executive_summary TEXT,
  ADD COLUMN internal_notes TEXT,
  ADD COLUMN status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
  ADD COLUMN is_existing_client BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN website_candidates JSONB NOT NULL DEFAULT '[]'::JSONB,
  ADD COLUMN website_pending_selection BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN ai_research_cached_at TIMESTAMPTZ,
  ADD COLUMN ai_research_raw JSONB,
  ADD COLUMN normalized_name TEXT,
  ADD COLUMN website_domain TEXT,
  ADD COLUMN manual_overrides JSONB NOT NULL DEFAULT '{}'::JSONB;

COMMENT ON COLUMN public.companies.normalized_name IS 'Lowercase normalized name for deduplication';
COMMENT ON COLUMN public.companies.website_domain IS 'Extracted domain for deduplication';
COMMENT ON COLUMN public.companies.manual_overrides IS 'Fields manually edited; AI refresh skips these keys';
COMMENT ON COLUMN public.companies.ai_research_raw IS 'Cached raw AI research response';

-- Backfill normalized names for existing rows
UPDATE public.companies
SET normalized_name = lower(regexp_replace(trim(company_name), '[^a-zA-Z0-9]+', '', 'g'))
WHERE normalized_name IS NULL;

-- Backfill website domains
UPDATE public.companies
SET website_domain = lower(
  regexp_replace(
    regexp_replace(coalesce(website, ''), '^https?://(www\.)?', '', 'i'),
    '/.*$',
    ''
  )
)
WHERE website IS NOT NULL AND website != '' AND website_domain IS NULL;

-- Dedup indexes (partial unique to allow nulls)
CREATE UNIQUE INDEX companies_normalized_name_unique
  ON public.companies (normalized_name)
  WHERE normalized_name IS NOT NULL AND normalized_name != '' AND status = 'active';

CREATE UNIQUE INDEX companies_website_domain_unique
  ON public.companies (website_domain)
  WHERE website_domain IS NOT NULL AND website_domain != '' AND status = 'active';

CREATE INDEX companies_status_idx ON public.companies (status);
CREATE INDEX companies_industry_idx ON public.companies (industry);
CREATE INDEX companies_created_at_idx ON public.companies (created_at);
CREATE INDEX companies_is_existing_client_idx ON public.companies (is_existing_client);

-- =============================================================================
-- 20260629000014_quote_builder.sql
-- =============================================================================

-- Quote Builder: extended quotes with deliverables and budget sections

CREATE TYPE public.discount_type AS ENUM ('percentage', 'fixed');

-- Extend quotes table
ALTER TABLE public.quotes
  ALTER COLUMN project_id DROP NOT NULL,
  ADD COLUMN quote_number TEXT,
  ADD COLUMN company_id UUID REFERENCES public.companies (id) ON DELETE SET NULL,
  ADD COLUMN contact_id UUID REFERENCES public.contacts (id) ON DELETE SET NULL,
  ADD COLUMN opportunity_id UUID REFERENCES public.opportunities (id) ON DELETE SET NULL,
  ADD COLUMN project_title TEXT,
  ADD COLUMN client_name TEXT,
  ADD COLUMN notes TEXT,
  ADD COLUMN discount_type public.discount_type NOT NULL DEFAULT 'fixed',
  ADD COLUMN discount_value NUMERIC(12, 2) NOT NULL DEFAULT 0,
  ADD COLUMN is_archived BOOLEAN NOT NULL DEFAULT false;

COMMENT ON COLUMN public.quotes.quote_number IS 'Auto-generated unique quote reference e.g. Q-2026-0001';
COMMENT ON COLUMN public.quotes.discount_value IS 'User-entered discount (percentage or fixed amount)';
COMMENT ON COLUMN public.quotes.discount IS 'Computed discount amount in currency';

-- Quote deliverables
CREATE TABLE public.quote_deliverables (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  quote_id UUID NOT NULL REFERENCES public.quotes (id) ON DELETE CASCADE,
  title TEXT NOT NULL DEFAULT '',
  description TEXT,
  quantity NUMERIC(10, 2) NOT NULL DEFAULT 1,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.quote_deliverables IS 'Deliverable line items on a quote';

-- Budget sections
CREATE TABLE public.quote_budget_sections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  quote_id UUID NOT NULL REFERENCES public.quotes (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.quote_budget_sections IS 'Budget category sections on a quote';

-- Budget line items
CREATE TABLE public.quote_budget_line_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  section_id UUID NOT NULL REFERENCES public.quote_budget_sections (id) ON DELETE CASCADE,
  description TEXT NOT NULL DEFAULT '',
  day_rate NUMERIC(12, 2) NOT NULL DEFAULT 0,
  num_days NUMERIC(10, 2) NOT NULL DEFAULT 0,
  total_cost NUMERIC(12, 2) NOT NULL DEFAULT 0,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.quote_budget_line_items IS 'Individual budget rows within a section';

-- Quote number generator
CREATE OR REPLACE FUNCTION public.generate_quote_number()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
  year_part TEXT := to_char(NOW(), 'YYYY');
  seq_num INTEGER;
BEGIN
  SELECT COALESCE(
    MAX(
      CASE
        WHEN quote_number ~ ('^Q-' || year_part || '-[0-9]+$')
        THEN CAST(split_part(quote_number, '-', 3) AS INTEGER)
        ELSE 0
      END
    ),
    0
  ) + 1
  INTO seq_num
  FROM public.quotes;

  RETURN 'Q-' || year_part || '-' || lpad(seq_num::TEXT, 4, '0');
END;
$$;

GRANT EXECUTE ON FUNCTION public.generate_quote_number() TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_quote_number() TO service_role;

-- Backfill quote numbers for any existing rows
UPDATE public.quotes
SET quote_number = public.generate_quote_number()
WHERE quote_number IS NULL;

ALTER TABLE public.quotes
  ALTER COLUMN quote_number SET NOT NULL;

CREATE UNIQUE INDEX quotes_quote_number_unique ON public.quotes (quote_number);
CREATE INDEX quotes_company_id_idx ON public.quotes (company_id);
CREATE INDEX quotes_opportunity_id_idx ON public.quotes (opportunity_id);
CREATE INDEX quotes_status_idx ON public.quotes (quote_status);
CREATE INDEX quotes_is_archived_idx ON public.quotes (is_archived);
CREATE INDEX quote_deliverables_quote_id_idx ON public.quote_deliverables (quote_id);
CREATE INDEX quote_budget_sections_quote_id_idx ON public.quote_budget_sections (quote_id);
CREATE INDEX quote_budget_line_items_section_id_idx ON public.quote_budget_line_items (section_id);

-- Updated_at triggers
CREATE TRIGGER quote_deliverables_updated_at
  BEFORE UPDATE ON public.quote_deliverables
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER quote_budget_sections_updated_at
  BEFORE UPDATE ON public.quote_budget_sections
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER quote_budget_line_items_updated_at
  BEFORE UPDATE ON public.quote_budget_line_items
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =============================================================================
-- 20260629000015_quote_builder_rls.sql
-- =============================================================================

-- RLS for quote builder tables

ALTER TABLE public.quote_deliverables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quote_budget_sections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quote_budget_line_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "quote_deliverables_all_authenticated"
  ON public.quote_deliverables FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "quote_budget_sections_all_authenticated"
  ON public.quote_budget_sections FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "quote_budget_line_items_all_authenticated"
  ON public.quote_budget_line_items FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- =============================================================================
-- 20260629000016_quote_pdf_export.sql
-- =============================================================================

-- Quote PDF export: expiry date and versioned PDF storage

ALTER TABLE public.quotes
  ADD COLUMN expiry_date DATE,
  ADD COLUMN current_pdf_version_id UUID;

CREATE TABLE public.quote_pdf_versions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  quote_id UUID NOT NULL REFERENCES public.quotes (id) ON DELETE CASCADE,
  version INTEGER NOT NULL,
  storage_path TEXT NOT NULL,
  file_size INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT quote_pdf_versions_quote_version_unique UNIQUE (quote_id, version)
);

ALTER TABLE public.quotes
  ADD CONSTRAINT quotes_current_pdf_version_id_fkey
  FOREIGN KEY (current_pdf_version_id)
  REFERENCES public.quote_pdf_versions (id)
  ON DELETE SET NULL;

COMMENT ON TABLE public.quote_pdf_versions IS 'Versioned PDF exports stored in Supabase Storage';
COMMENT ON COLUMN public.quotes.expiry_date IS 'Quote validity expiry date shown on PDF';

CREATE INDEX quote_pdf_versions_quote_id_idx ON public.quote_pdf_versions (quote_id);
CREATE INDEX quotes_current_pdf_version_id_idx ON public.quotes (current_pdf_version_id);

-- Default expiry: 30 days from creation for existing quotes
UPDATE public.quotes
SET expiry_date = (created_at::DATE + INTERVAL '30 days')
WHERE expiry_date IS NULL;

-- =============================================================================
-- 20260629000017_quote_pdf_rls.sql
-- =============================================================================

-- RLS for quote PDF versions

ALTER TABLE public.quote_pdf_versions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "quote_pdf_versions_all_authenticated"
  ON public.quote_pdf_versions FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- =============================================================================
-- 20260629000018_production_schedule_builder.sql
-- =============================================================================

-- Production Schedule Builder: extended schedules with version history

ALTER TABLE public.production_schedules
  ALTER COLUMN project_id DROP NOT NULL,
  ADD COLUMN company_id UUID REFERENCES public.companies (id) ON DELETE SET NULL,
  ADD COLUMN opportunity_id UUID REFERENCES public.opportunities (id) ON DELETE SET NULL,
  ADD COLUMN quote_id UUID REFERENCES public.quotes (id) ON DELETE SET NULL,
  ADD COLUMN project_title TEXT NOT NULL DEFAULT 'Untitled Production Schedule',
  ADD COLUMN start_date DATE,
  ADD COLUMN delivery_date DATE,
  ADD COLUMN review_rounds INTEGER NOT NULL DEFAULT 2,
  ADD COLUMN deliverables TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN notes TEXT,
  ADD COLUMN status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('draft', 'active', 'archived')),
  ADD COLUMN current_version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE public.production_schedules
  DROP CONSTRAINT IF EXISTS production_schedules_project_version_unique;

-- Version history snapshots
CREATE TABLE public.production_schedule_versions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  schedule_id UUID NOT NULL REFERENCES public.production_schedules (id) ON DELETE CASCADE,
  version INTEGER NOT NULL,
  schedule_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  change_note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT production_schedule_versions_schedule_version_unique
    UNIQUE (schedule_id, version)
);

COMMENT ON TABLE public.production_schedule_versions IS 'Version history snapshots for production schedules';
COMMENT ON COLUMN public.production_schedules.schedule_json IS 'Current schedule data: phases and milestones';

-- Migrate existing version numbers into current_version
UPDATE public.production_schedules
SET current_version = version
WHERE current_version = 1 AND version > 1;

-- Seed version history from existing rows
INSERT INTO public.production_schedule_versions (schedule_id, version, schedule_json)
SELECT id, COALESCE(version, 1), schedule_json
FROM public.production_schedules
ON CONFLICT (schedule_id, version) DO NOTHING;

ALTER TABLE public.production_schedules DROP COLUMN IF EXISTS version;

CREATE INDEX production_schedules_company_id_idx ON public.production_schedules (company_id);
CREATE INDEX production_schedules_quote_id_idx ON public.production_schedules (quote_id);
CREATE INDEX production_schedules_opportunity_id_idx ON public.production_schedules (opportunity_id);
CREATE INDEX production_schedules_status_idx ON public.production_schedules (status);
CREATE INDEX production_schedules_delivery_date_idx ON public.production_schedules (delivery_date);
CREATE INDEX production_schedule_versions_schedule_id_idx
  ON public.production_schedule_versions (schedule_id);

-- =============================================================================
-- 20260629000019_production_schedule_rls.sql
-- =============================================================================

-- RLS for production schedule versions

ALTER TABLE public.production_schedule_versions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "production_schedule_versions_all_authenticated"
  ON public.production_schedule_versions FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- =============================================================================
-- 20260629000020_production_schedule_pdf_export.sql
-- =============================================================================

-- Production schedule PDF export: versioned PDF storage

ALTER TABLE public.production_schedules
  ADD COLUMN current_pdf_version_id UUID;

CREATE TABLE public.production_schedule_pdf_versions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  schedule_id UUID NOT NULL REFERENCES public.production_schedules (id) ON DELETE CASCADE,
  version INTEGER NOT NULL,
  storage_path TEXT NOT NULL,
  file_size INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT production_schedule_pdf_versions_schedule_version_unique
    UNIQUE (schedule_id, version)
);

ALTER TABLE public.production_schedules
  ADD CONSTRAINT production_schedules_current_pdf_version_id_fkey
  FOREIGN KEY (current_pdf_version_id)
  REFERENCES public.production_schedule_pdf_versions (id)
  ON DELETE SET NULL;

COMMENT ON TABLE public.production_schedule_pdf_versions IS
  'Versioned production schedule PDF exports stored in Supabase Storage';

CREATE INDEX production_schedule_pdf_versions_schedule_id_idx
  ON public.production_schedule_pdf_versions (schedule_id);

CREATE INDEX production_schedules_current_pdf_version_id_idx
  ON public.production_schedules (current_pdf_version_id);

ALTER TABLE public.production_schedule_pdf_versions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "production_schedule_pdf_versions_all_authenticated"
  ON public.production_schedule_pdf_versions FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- =============================================================================
-- 20260629000021_projects_module.sql
-- =============================================================================

-- Projects module: extended schema, deliverables, notes, files

CREATE TYPE public.project_priority AS ENUM (
  'low',
  'medium',
  'high',
  'urgent'
);

-- Migrate project_status to new workflow values
ALTER TABLE public.projects ALTER COLUMN status DROP DEFAULT;
ALTER TABLE public.projects ALTER COLUMN status TYPE TEXT USING status::TEXT;

UPDATE public.projects SET status = CASE status
  WHEN 'draft' THEN 'planning'
  WHEN 'active' THEN 'in_progress'
  WHEN 'on_hold' THEN 'waiting_for_client'
  WHEN 'in_review' THEN 'review'
  WHEN 'completed' THEN 'complete'
  WHEN 'cancelled' THEN 'archived'
  ELSE 'planning'
END;

DROP TYPE public.project_status;

CREATE TYPE public.project_status AS ENUM (
  'planning',
  'in_progress',
  'waiting_for_client',
  'rendering',
  'review',
  'complete',
  'archived'
);

ALTER TABLE public.projects
  ALTER COLUMN status TYPE public.project_status
  USING status::public.project_status;

ALTER TABLE public.projects
  ALTER COLUMN status SET DEFAULT 'planning';

-- Extend projects with workspace fields and direct links
ALTER TABLE public.projects
  ADD COLUMN company_id UUID REFERENCES public.companies (id) ON DELETE SET NULL,
  ADD COLUMN contact_id UUID REFERENCES public.contacts (id) ON DELETE SET NULL,
  ADD COLUMN opportunity_id UUID REFERENCES public.opportunities (id) ON DELETE SET NULL,
  ADD COLUMN quote_id UUID REFERENCES public.quotes (id) ON DELETE SET NULL,
  ADD COLUMN producer TEXT,
  ADD COLUMN team_members TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN priority public.project_priority NOT NULL DEFAULT 'medium',
  ADD COLUMN budget NUMERIC(12, 2),
  ADD COLUMN notes TEXT,
  ADD COLUMN progress INTEGER NOT NULL DEFAULT 0
    CHECK (progress >= 0 AND progress <= 100);

-- Backfill company_id from clients
UPDATE public.projects p
SET company_id = c.company_id
FROM public.clients c
WHERE p.client_id = c.id
  AND p.company_id IS NULL;

CREATE INDEX projects_company_id_idx ON public.projects (company_id);
CREATE INDEX projects_status_idx ON public.projects (status);
CREATE INDEX projects_delivery_date_idx ON public.projects (delivery_date)
  WHERE delivery_date IS NOT NULL;
CREATE INDEX projects_quote_id_idx ON public.projects (quote_id);

-- Project deliverables
CREATE TABLE public.project_deliverables (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES public.projects (id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  is_complete BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX project_deliverables_project_id_idx
  ON public.project_deliverables (project_id);

-- Project notes (internal, chronological)
CREATE TABLE public.project_notes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES public.projects (id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX project_notes_project_id_idx ON public.project_notes (project_id);

-- Project files (stored in project-assets bucket)
CREATE TABLE public.project_files (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id UUID NOT NULL REFERENCES public.projects (id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  storage_path TEXT NOT NULL,
  mime_type TEXT,
  file_size INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX project_files_project_id_idx ON public.project_files (project_id);

-- Updated-at triggers
CREATE TRIGGER project_deliverables_updated_at
  BEFORE UPDATE ON public.project_deliverables
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER project_notes_updated_at
  BEFORE UPDATE ON public.project_notes
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- RLS
ALTER TABLE public.project_deliverables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_files ENABLE ROW LEVEL SECURITY;

CREATE POLICY "project_deliverables_all_authenticated"
  ON public.project_deliverables FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "project_notes_all_authenticated"
  ON public.project_notes FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "project_files_all_authenticated"
  ON public.project_files FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

COMMENT ON TABLE public.project_deliverables IS 'Trackable deliverables per project';
COMMENT ON TABLE public.project_notes IS 'Internal chronological notes per project';
COMMENT ON TABLE public.project_files IS 'Files uploaded to project-assets storage';

-- =============================================================================
-- 20260629000022_settings_team_management.sql
-- =============================================================================

-- Settings & Team Management

CREATE TYPE public.user_role AS ENUM (
  'administrator',
  'producer',
  'creative_director',
  'designer',
  'freelancer',
  'viewer'
);

CREATE TYPE public.team_member_status AS ENUM (
  'active',
  'inactive'
);

CREATE TABLE public.app_settings (
  id TEXT PRIMARY KEY DEFAULT 'default' CHECK (id = 'default'),
  company_name TEXT NOT NULL DEFAULT 'Dissembargo',
  company_logo_url TEXT,
  company_address TEXT DEFAULT 'London, United Kingdom',
  company_email TEXT DEFAULT 'hello@dissembargo.com',
  company_phone TEXT,
  website TEXT DEFAULT 'www.dissembargo.com',
  default_currency TEXT NOT NULL DEFAULT 'GBP',
  timezone TEXT NOT NULL DEFAULT 'Europe/London',
  default_language TEXT NOT NULL DEFAULT 'en-GB',
  quote_validity_days INTEGER NOT NULL DEFAULT 30,
  default_budget_sections JSONB NOT NULL DEFAULT '["Studio Leads","Design","Modelling","Animation","Lighting","Rendering","Editing","Music","Miscellaneous"]'::JSONB,
  default_day_rates JSONB NOT NULL DEFAULT '{}'::JSONB,
  default_discount_type public.discount_type NOT NULL DEFAULT 'fixed',
  default_discount_value NUMERIC(12, 2) NOT NULL DEFAULT 0,
  default_terms JSONB NOT NULL DEFAULT '[]'::JSONB,
  default_phases JSONB NOT NULL DEFAULT '["Scoping","Research","Look Development","Design","Modelling","Animation","Lighting","Rendering","Compositing","Client Review","Final Delivery"]'::JSONB,
  phase_weights JSONB NOT NULL DEFAULT '{}'::JSONB,
  default_milestones JSONB NOT NULL DEFAULT '["kick_off","wip_review","client_feedback","client_approval","final_delivery"]'::JSONB,
  default_review_rounds INTEGER NOT NULL DEFAULT 2,
  default_schedule_duration_days INTEGER NOT NULL DEFAULT 42,
  working_days JSONB NOT NULL DEFAULT '[1,2,3,4,5]'::JSONB,
  company_holidays JSONB NOT NULL DEFAULT '[]'::JSONB,
  email_signature TEXT,
  pdf_header_logo_url TEXT,
  pdf_footer_text TEXT,
  pdf_tagline TEXT DEFAULT 'Creative Production Studio',
  pdf_colors JSONB NOT NULL DEFAULT '{"primary":"#18181b","accent":"#6366f1","accentLight":"#eef2ff","muted":"#71717a","border":"#e4e4e7","background":"#ffffff","surface":"#fafafa"}'::JSONB,
  notify_email BOOLEAN NOT NULL DEFAULT TRUE,
  notify_deadlines BOOLEAN NOT NULL DEFAULT TRUE,
  notify_quote_approval BOOLEAN NOT NULL DEFAULT TRUE,
  notify_client_feedback BOOLEAN NOT NULL DEFAULT TRUE,
  notify_ai_processing BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.team_members (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  job_title TEXT,
  day_rate NUMERIC(10, 2),
  department TEXT,
  avatar_url TEXT,
  status public.team_member_status NOT NULL DEFAULT 'active',
  role public.user_role NOT NULL DEFAULT 'viewer',
  profile_id UUID REFERENCES public.profiles (id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT team_members_email_unique UNIQUE (email)
);

CREATE INDEX team_members_status_idx ON public.team_members (status);
CREATE INDEX team_members_role_idx ON public.team_members (role);

CREATE TRIGGER app_settings_updated_at
  BEFORE UPDATE ON public.app_settings
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER team_members_updated_at
  BEFORE UPDATE ON public.team_members
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;

CREATE POLICY "app_settings_all_authenticated"
  ON public.app_settings FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "team_members_all_authenticated"
  ON public.team_members FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Seed default settings row
INSERT INTO public.app_settings (id)
VALUES ('default')
ON CONFLICT (id) DO NOTHING;

-- Seed default terms from existing PDF defaults
UPDATE public.app_settings
SET default_terms = '[
  "This quotation is valid until the expiry date stated above. Prices are quoted in GBP and exclude VAT unless otherwise stated.",
  "A 50% deposit is required to commence work. The remaining balance is due upon delivery of final assets, unless alternative payment terms are agreed in writing.",
  "Scope is limited to the deliverables listed in this document. Additional revisions, assets, or services outside the agreed scope will be quoted separately.",
  "Client-supplied materials must be cleared for use. Dissembargo is not liable for delays caused by incomplete briefs, feedback, or third-party dependencies.",
  "Final project files will be released upon receipt of full payment. Usage rights are granted as specified in the project agreement.",
  "Cancellation after project commencement may incur fees for work completed to date. Deposits are non-refundable once production has begun.",
  "Dissembargo retains the right to showcase completed work in its portfolio unless a confidentiality agreement is in place."
]'::JSONB,
phase_weights = '{
  "Scoping": 1,
  "Research": 1,
  "Look Development": 2,
  "Design": 2,
  "Modelling": 3,
  "Animation": 4,
  "Lighting": 2,
  "Rendering": 2,
  "Compositing": 2,
  "Client Review": 1,
  "Final Delivery": 1
}'::JSONB
WHERE id = 'default';

-- =============================================================================
-- 20260630000001_quote_version_label.sql
-- =============================================================================

-- User-editable quote version label (e.g. V1, Draft, Final)

ALTER TABLE public.quotes
  ADD COLUMN IF NOT EXISTS version TEXT;

COMMENT ON COLUMN public.quotes.version IS
  'User-facing quote version label e.g. V1, Draft, Final, Rev A';

UPDATE public.app_settings
SET default_budget_sections =
  '["Creative Direction","Design","Modelling","Animation","Lighting","Rendering","Editing","Music","Miscellaneous"]'::jsonb
WHERE id = 'default'
  AND default_budget_sections::text LIKE '%Studio Leads%';

-- =============================================================================
-- 20260630000002_inbox_ai_improvements.sql
-- =============================================================================

-- Extend AI email categories
ALTER TYPE public.ai_email_category ADD VALUE IF NOT EXISTS 'newsletter';
ALTER TYPE public.ai_email_category ADD VALUE IF NOT EXISTS 'internal';

-- Opportunity fields for AI-extracted enquiry details
ALTER TABLE public.opportunities
  ADD COLUMN IF NOT EXISTS requested_deliverables TEXT;

COMMENT ON COLUMN public.opportunities.requested_deliverables IS
  'Creative deliverables requested in the source email, extracted by AI';

-- Human feedback on AI classification decisions (for future model improvement)
CREATE TABLE IF NOT EXISTS public.ai_classification_feedback (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  inbox_id UUID NOT NULL REFERENCES public.inbox (id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  original_category public.ai_email_category,
  corrected_category public.ai_email_category,
  original_confidence NUMERIC(5, 2),
  feedback_action TEXT NOT NULL CHECK (
    feedback_action IN ('approved', 'rejected', 'reclassified', 'manual_created')
  ),
  company_name_override TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_classification_feedback_inbox_id
  ON public.ai_classification_feedback (inbox_id);

CREATE INDEX IF NOT EXISTS idx_ai_classification_feedback_user_id
  ON public.ai_classification_feedback (user_id);

CREATE INDEX IF NOT EXISTS idx_ai_classification_feedback_created_at
  ON public.ai_classification_feedback (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_inbox_ai_category
  ON public.inbox (ai_category);

COMMENT ON TABLE public.ai_classification_feedback IS
  'Human corrections to AI email classifications for future model training';

-- =============================================================================
-- 20260630000003_gmail_multiple_accounts.sql
-- =============================================================================

-- Support multiple Gmail accounts per user
ALTER TABLE public.gmail_connections
  DROP CONSTRAINT IF EXISTS gmail_connections_user_id_key;

CREATE UNIQUE INDEX IF NOT EXISTS gmail_connections_user_address_unique
  ON public.gmail_connections (user_id, gmail_address);

-- Track which Gmail account imported each email
ALTER TABLE public.inbox
  ADD COLUMN IF NOT EXISTS gmail_connection_id UUID
  REFERENCES public.gmail_connections (id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_inbox_gmail_connection_id
  ON public.inbox (gmail_connection_id);

COMMENT ON INDEX public.gmail_connections_user_address_unique IS
  'Each user can connect multiple Gmail accounts, but not the same address twice';

-- =============================================================================
-- 20260701000001_potential_opportunities.sql
-- =============================================================================

-- Potential Opportunities: AI-staged business development leads from Gmail

CREATE TYPE public.potential_opportunity_status AS ENUM (
  'pending',
  'accepted',
  'dismissed'
);

CREATE TABLE public.potential_opportunities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  inbox_id UUID NOT NULL UNIQUE REFERENCES public.inbox (id) ON DELETE CASCADE,
  company_id UUID REFERENCES public.companies (id) ON DELETE SET NULL,
  contact_id UUID REFERENCES public.contacts (id) ON DELETE SET NULL,
  opportunity_id UUID REFERENCES public.opportunities (id) ON DELETE SET NULL,
  status public.potential_opportunity_status NOT NULL DEFAULT 'pending',
  company_name TEXT NOT NULL,
  contact_name TEXT,
  contact_email TEXT,
  contact_phone TEXT,
  company_website TEXT,
  project_name TEXT,
  project_description TEXT,
  deliverables TEXT,
  estimated_budget NUMERIC(12, 2),
  deadline TEXT,
  location TEXT,
  ai_summary TEXT NOT NULL,
  ai_confidence NUMERIC(5, 2) NOT NULL CHECK (ai_confidence >= 0 AND ai_confidence <= 100),
  ai_reasoning TEXT,
  extraction_json JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.potential_opportunities IS
  'AI-identified job enquiries surfaced in the Inbox business development assistant';

CREATE INDEX potential_opportunities_user_status_idx
  ON public.potential_opportunities (user_id, status);

CREATE INDEX potential_opportunities_company_id_idx
  ON public.potential_opportunities (company_id);

CREATE INDEX potential_opportunities_created_at_idx
  ON public.potential_opportunities (created_at DESC);

CREATE TRIGGER potential_opportunities_updated_at
  BEFORE UPDATE ON public.potential_opportunities
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.potential_opportunities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "potential_opportunities_all_authenticated"
  ON public.potential_opportunities FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Extend inbox review_status for ignored non-job mail
ALTER TYPE public.inbox_review_status ADD VALUE IF NOT EXISTS 'ignored';
