name: Deploy Expo Web to GitHub Pages

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build Expo web
      run: npm run build:web

    - name: Prepare docs folder
      run: |
        rm -rf docs
        mv web-build docs

    - name: Deploy to GitHub Pages

      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
